import React from "react";
import { Tajawal } from "next/font/google";
import "./globals.css";
import ReactQueryProvider from "@/providers/ReactQueryProvider";
import ReduxProvider from "@/providers/ReduxProvider";
import LayoutSelectorProvider from "@/providers/LayoutSelectorProvider";

const tajawal = Tajawal({ subsets: ["latin"], weight: ["400", "700"] });

export const metadata = {
  title: "Beauty Cosmetic",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${tajawal.className} antialiased`}>
        <ReactQueryProvider>
        <ReduxProvider>
          <LayoutSelectorProvider>{children}</LayoutSelectorProvider>
        </ReduxProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}